# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
solc_version = '0.8.17'
fuzz_runs = 500
libs = ['lib']
optimizer = true
optimizer_runs = 500000
out = 'dist/artifacts'
src = 'src'
test = 'test'
fs_permissions = [{ access = "read-write", path = "./"}, { access = "read-write", path = "../../node_modules"}]
allow_paths = ["../../node_modules"]
block_timestamp = 1676667157361
gas_reports = ["Manager", "Milestones", "Intervals"]

[rpc_endpoints]
goerli = "${RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBSCAN_API_KEY}", url="https://api.arbiscan.io" }
optimism = { key = "${OPTSCAN_API_KEY}" }
polygon = { key = "${POLYSCAN_API_KEY}" }