export enum ErrorCodes {
  NOT_NFT_VOTING_MODULE = 'NOT_NFT_VOTING_MODULE',
  VOTING_MODULE_NOT_FOUND = 'VOTING_MODULE_NOT_FOUND',
  INVALID_NFT_COLLECTION_INFO = 'INVALID_NFT_COLLECTION_INFO',
  NOT_DAO_DAO_CORE = 'NOT_DAO_DAO_CORE',
}
