name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    env:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
      OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    defaults:
      run:
        working-directory: apps/web3
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run local tests
        run: yarn test

      - name: Run goerli fork tests
        run: yarn github:test:goerli

      - name: Run mainnet fork tests
        run: yarn github:test:mainnet

      - name: Run optimism fork tests
        run: yarn github:test:optimism
